server: # server configuration ,
  addr: 0.0.0.0:443 # SERVER_ADDRESS - address to bind to
  tls:
    cert: # SERVER_TLS_CERT - tls certificate
    key: # SERVER_TLS_KEY - tls private key

rso:
  base_url: "https://auth.riotgames.com" # RSO_BASE_URL - Riot Games oauth auth provider URL
  callback_host: "https://local.example.com" # RSO_CALLBACK_HOST - callback hostname
  client_id: "" # RSO_CLIENT_ID - oauth2 client id
  client_secret: "" # RSO_CLIENT_SECRET - oauth2 client secret

api:
  token: "" # Riot Games API token - RGAPI_TOKEN
  urls:
    account_data: "https://americas.api.riotgames.com/riot/account/v1/accounts/me" # RGAPI_URL_ACCOUNT_DATA - Riot Games API account data URL
    champion_data: "https://na1.api.riotgames.com/lol/platform/v3/champion-rotations" # RGAPI_URL_CHAMPION_DATA - Riot Games API champion data URL

