on: [push, pull_request]

name: rso_sample_apps_rust

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo check
        working-directory: ./sample_apps/rso_sample_apps/rust

  test:
    name: test
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo test
        working-directory: ./sample_apps/rso_sample_apps/rust

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
        working-directory: ./sample_apps/rso_sample_apps/rust

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
        working-directory: ./sample_apps/rso_sample_apps/rust
